/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/Landscape.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody, Debug } from '@react-three/rapier'

const Landscape = ({ fixed, ...props }) => {
  const { nodes, materials } = useGLTF('./models/Landscape.gltf')
  return (
    <>
      <Debug />
      <RigidBody fixed colliders={'trimesh'} restitution={0.3}>
        <group {...props} dispose={null}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Text.geometry}
            material={nodes.Text.material}
            position={[-8.82, 6.47, -5.55]}
            rotation={[Math.PI / 2, 0, -0.92]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Map.geometry}
            material={materials['Material.004']}
            position={[0, 0.05, 0]}
          />
        </group>
      </RigidBody>
    </>
  )
}

useGLTF.preload('./models/Landscape.gltf')

export default Landscape
