/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/Landscape.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody, Debug } from '@react-three/rapier'

const Landscape = ({ fixed, ...props }) => {
  const { nodes, materials } = useGLTF('./models/Landscape.gltf')
  return (
    <>
      <Debug />
      <RigidBody fixed colliders={'trimesh'} restitution={0.3}>
        <group {...props} dispose={null}>
          <mesh
            geometry={nodes['Sculpting_map-s2'].geometry}
            material={materials['Material.005']}
          />
        </group>
      </RigidBody>
    </>
  )
}

useGLTF.preload('./models/Landscape.gltf')

export default Landscape
