/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/man.gltf
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Man = (props)=>  {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/man.gltf')
  const { actions, names } = useAnimations(animations, group)

  // useEffect(() => {
  //   actions[names[0]].reset().fadeIn(0.5).play();
  // }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh name="Cube" geometry={nodes.Cube.geometry} material={nodes.Cube.material} skeleton={nodes.Cube.skeleton} />
      </group>
    </group>
  )
} 

useGLTF.preload('./models/man.gltf')

export default Man