/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/Landscape.gltf
*/

import { useGLTF } from '@react-three/drei'
import { RigidBody, CuboidCollider } from '@react-three/rapier'

const Landscape = ({ debug = false, ...props }) => {
  const { nodes, materials } = useGLTF('../assets/models/Landscape.gltf')
  return (
    <>
      {/* {debug && <Debug />*/}
      <RigidBody type="fixed" colliders={'trimesh'}>
        <group {...props} dispose={null}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Text.geometry}
            material={nodes.Text.material}
            position={[-8.82, 6.47, -5.55]}
            rotation={[Math.PI / 2, 0, -0.92]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Map.geometry}
            material={materials['Material.004']}
            position={[0, 0.05, 0]}
          />
        </group>
      </RigidBody>
    </>
  )
}

useGLTF.preload('../assets/models/Landscape.gltf')

export default Landscape
