/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Lumberjack.gltf
Author: micaelsampaio (https://sketchfab.com/micaelsampaio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lumberjack-low-poly-character-d88d033c86a243f78349f935f78ba057
Title: Lumberjack Low Poly Character
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Lumberjack = (props) => {
  const { nodes, materials } = useGLTF('../assets/models/Lumberjack.gltf')
  return (
    <group position={[0, 1, 0]} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.Material}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('../assets/models/Lumberjack.gltf')

export default Lumberjack
